import { Contact } from "@container/Contact";
import { Custom } from "@container/Custom";
import { Footer } from "@container/Footer";
import { Header } from "@container/Header";
import { Hero } from "@container/Hero";
import { motion } from "framer-motion";
import { Offers } from "@container/Offers";
import Head from "next/head";
import { RefObject, useRef } from "react";

export default function Home() {
  const targetSectionRef: RefObject<HTMLElement> = useRef(null);

  const handleClick = () => {
    if (targetSectionRef.current) {
      targetSectionRef.current.scrollIntoView({ behavior: "smooth" });
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <motion.section
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          <Hero customClick={handleClick} />
          <Offers />
          <Custom targetRef={targetSectionRef} />
          <Contact />
          <Footer />
        </motion.section>
      </main>
    </>
  );
}
